export const PTS = {
  WE: 'WHITE',
  BK: 'BLACK',
  RD: 'RED'
}

export const BoardModel = [
  [PTS.WE, PTS.BK, PTS.BK, PTS.WE, PTS.BK, PTS.BK, PTS.WE],
  [PTS.BK, PTS.RD, PTS.WE, PTS.RD, PTS.WE, PTS.RD, PTS.BK],
  [PTS.WE, PTS.BK, PTS.BK, PTS.BK, PTS.RD, PTS.BK, PTS.WE],
  [PTS.BK, PTS.WE, PTS.BK, PTS.RD, PTS.BK, PTS.WE, PTS.BK],
  [PTS.WE, PTS.BK, PTS.RD, PTS.BK, PTS.BK, PTS.BK, PTS.WE],
  [PTS.BK, PTS.RD, PTS.WE, PTS.RD, PTS.WE, PTS.RD, PTS.BK],
  [PTS.WE, PTS.BK, PTS.BK, PTS.WE, PTS.BK, PTS.BK, PTS.WE]
]
